### PR TITLE
Pulling in certimporter improvements

### PR DESCRIPTION
**Pull request by oxtoacart**

### CODE REVIEW

**Comment by oxtoacart** [comment]
@jeffreydwalter This pulls your changes (with some tweaks of mine) into master.

**Comment by jeffreydwalter** [comment]
Awesome! Out of curiosity, why did you recompile certimporter? What all did you change? It wasn't obvious to me from the commits.

Thanks!
Jeff

**Comment by oxtoacart** [comment]
@jeffreydwalter I just recompiled for security reasons. We distribute this to a bunch of users and I don't want to take any chances with accepting binaries.

Thanks very much for your PR, it actually added a feature that I would have had to add for myself soon! I'm also glad to see someone getting use out of this library :)

**Comment by jeffreydwalter** [comment]
@oxtoacart makes perfect sense. Thanks for the great library! I'm glad my changes are useful to you. After such a long time, I was starting to think this was a dead repo. :)

Did you happen to compile the binary with static linking? That was the one of the things I hit upon while testing the changes I made. I had originally neglected to do that and it caused issues.

**Comment by oxtoacart** [comment]
Okay, binary is now statically linked. I also added a little trustdemo program which exercises the API so that we can smoke test it on the different platforms.

**Comment by jeffreydwalter** [comment]
Awesome, thank you!

**Pull request merged**
